version: '3.1'

services:

  db:
    build: testdb
    # command: --default-authentication-plugin=mysql_native_password
    restart: always

  frontend:
    image: testfront
    restart: always
    environment:
      DB_HOST: database
    links:
      - db:database
    ports:
      - 80:80
    depends_on:
      - db